# Generated by Django 2.1.7 on 2019-03-27 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_kit', models.CharField(max_length=50)),
                ('observaciones', models.CharField(max_length=200)),
                ('ubicacion_kit', models.CharField(max_length=50)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Colegio')),
            ],
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sensor', models.CharField(max_length=50)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Kit')),
            ],
        ),
    ]
