# Generated by Django 2.1.7 on 2019-03-27 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0003_anemometro_ch4_co_co2_humedad_luzuv_materialorganico_materialparticulado_metanopropanoco_no2_o3_polv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semillero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsable', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Colegio')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Kit')),
            ],
        ),
        migrations.AddField(
            model_name='integrantes',
            name='semillero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_praes.Semillero'),
        ),
    ]
