# Generated by Django 2.1.7 on 2019-03-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0004_auto_20190327_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensores',
            name='observaciones',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='kit',
            name='observaciones',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
