# Generated by Django 2.1.7 on 2019-03-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_praes', '0005_auto_20190327_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='telefono',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
